### ISSUE TITLE
Update checklist

### ISSUE THREAD

**Issue by StevenBlack** [QueensSailing/QueensSailing.github.io#18]
List of things that need updating on luff.ca

- [ ] Many 2017 articles appear on gogaelsgo but don't here.  Cross-check http://gogaelsgo.com/archives.aspx?path=sail
- [ ] **Bold** individual names in recent articles.
- [ ] Explicitly thank Lindsey Fair in the [Try Varsity Sailing Recap](http://luff.ca/2017/try-varsity-sailing.html)
- [ ] Re-title the [Try Varsity Sailing Recap](http://luff.ca/2017/try-varsity-sailing.html) because the current title is just wrong.
- [ ] Need a season recap

**Comment by ch-black** [comment]
Have fixed and updated the "Try Varsity Sailing" page.
Have made a burgee/fundraising post. Will need to make it more prominent (+ add "donate" button?)
"RECRUITS!" aka luff.ca/prospect is updated for the 2018 tryout. 
Need to figure out Shopify because my free trial expired.

**Comment by StevenBlack** [comment]
@ch-black try calling Shopify at 1 (888) 746-7439 to get that trial extended?
